name: Create Change Log
on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
jobs:
  bump_tag:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Generate and Commit Changelog

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Generate Changelog
      uses: smichard/conventional_changelog@2.0.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Git User Info
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'

    - name: Commit Changelog
      run: |
        git add 'CHANGELOG.md'
        git commit -m "chore: :robot: changelog file generated" || echo "No changes to commit"
        git push
